Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

